export type ToolbarItem =
  | 'emoji'
  | 'headings'
  | 'bold'
  | 'italic'
  | 'strike'
  | '|'
  | 'line'
  | 'quote'
  | 'list'
  | 'ordered-list'
  | 'check'
  | 'outdent'
  | 'indent'
  | 'code'
  | 'inline-code'
  | 'insert-after'
  | 'insert-before'
  | 'undo'
  | 'redo'
  | 'upload'
  | 'link'
  | 'table'
  | 'record'
  | 'edit-mode'
  | 'both'
  | 'preview'
  | 'fullscreen'
  | 'outline'
  | 'code-theme'
  | 'content-theme'
  | 'export'
  | 'devtools'
  | 'info'
  | 'help'
  | 'br'

export type LangType = 'zh_CN' | 'en_US' | 'zh_TW' | 'ru_RU' | 'ko_KR' | 'ja_JP'

export type ModeType = 'sv' | 'ir' | 'wysiwyg'

export type ThemeType = 'classic' | 'dark'

export type IconType = 'ant' | 'material'
